# SDV
- https://pypi.org/project/sdv/

In [2]:
#pip install sdv

In [3]:
from sdv.datasets.demo import download_demo

real_data, metadata = download_demo(modality='single_table', dataset_name='fake_hotel_guests')

In [4]:
real_data

,guest_email,has_rewards,room_type,amenities_fee,checkin_date,checkout_date,room_rate,billing_address,credit_card_number
0,michaelsanders@shaw.net,False,BASIC,37.89,27 Dec 2020,29 Dec 2020,131.23,"49380 Rivers Street\nSpencerville, AK 68265",4075084747483975747
1,randy49@brown.biz,False,BASIC,24.37,30 Dec 2020,02 Jan 2021,114.43,"88394 Boyle Meadows\nConleyberg, TN 22063",180072822063468
2,webermelissa@neal.com,True,DELUXE,0.00,17 Sep 2020,18 Sep 2020,368.33,"0323 Lisa Station Apt. 208\nPort Thomas, LA 82585",38983476971380
3,gsims@terry.com,False,BASIC,NaN,28 Dec 2020,31 Dec 2020,115.61,"77 Massachusetts Ave\nCambridge, MA 02139",4969551998845740
4,misty33@smith.biz,False,BASIC,16.45,05 Apr 2020,NaN,122.41,"1234 Corporate Drive\nBoston, MA 02116",3558512986488983
...,...,...,...,...,...,...,...,...,...
495,laurabennett@jones-duncan.net,False,BASIC,8.71,04 Jan 2021,06 Jan 2021,103.25,"5678 Office Road\nSan Francisco, CA 94103",3505516387300030
496,johnny71@cook.info,False,BASIC,16.31,24 Aug 2020,26 Aug 2020,115.81,"953 White Island\nChristopherside, TN 91366",2224524502892552
497,ygarcia@ballard-lopez.net,False,BASIC,30.59,11 Nov 2020,13 Nov 2020,141.61,"5678 Office Road\nSan Francisco, CA 94103",180096250673548
498,thomasdale@hall.com,False,BASIC,1.93,16 Jul 2020,18 Jul 2020,136.92,"5678 Office Road\nSan Francisco, CA 94103",4488223821722
499,danieltaylor@harper.com,False,BASIC,3.84,22 Mar 2020,25 Mar 2020,143.52,"034 Tran Oval\nHowardshire, VT 40933",213165812201188

In [5]:
from sdv.single_table import GaussianCopulaSynthesizer

synthesizer = GaussianCopulaSynthesizer(metadata)
synthesizer.fit(data=real_data)

In [6]:
synthetic_data = synthesizer.sample(num_rows=500)

In [7]:
synthetic_data

,guest_email,has_rewards,room_type,amenities_fee,checkin_date,checkout_date,room_rate,billing_address,credit_card_number
0,dsullivan@example.net,False,BASIC,0.29,27 Mar 2020,09 Mar 2020,135.15,"90469 Karla Knolls Apt. 781\nSusanberg, CA 70033",5161033759518983
1,steven59@example.org,False,DELUXE,8.15,07 Sep 2020,25 Jun 2020,183.24,"6108 Carla Ports Apt. 116\nPort Evan, MI 71694",4133047413145475690
2,brandon15@example.net,False,BASIC,11.65,22 Mar 2020,01 Apr 2020,163.57,86709 Jeremy Manors Apt. 786\nPort Garychester...,4977328103788
3,humphreyjennifer@example.net,False,BASIC,48.12,04 Jun 2020,14 May 2020,127.75,"8906 Bobby Trail\nEast Sandra, NY 43986",3524946844839485
4,joshuabrown@example.net,False,DELUXE,11.07,08 Jan 2020,13 Jan 2020,180.12,"732 Dennis Lane\nPort Nicholasstad, DE 49786",4446905799576890978
...,...,...,...,...,...,...,...,...,...
495,donnaodom@example.net,False,DELUXE,NaN,14 Jan 2020,15 Jan 2020,276.74,"328 Danny Haven Apt. 575\nBrownbury, FM 31800",180069262819334
496,tammycarey@example.net,False,DELUXE,0.91,14 May 2020,23 Mar 2020,271.57,"48578 Parker Underpass\nBradybury, VA 45723",4716059563401606
497,gwebb@example.org,True,BASIC,1.43,18 Mar 2020,27 Feb 2020,131.85,"590 Peterson Roads Apt. 892\nLake Phillip, NE ...",3564840847844629
498,carlnovak@example.com,False,BASIC,48.12,29 Jun 2020,25 Aug 2020,367.12,"2854 Steven Haven\nWest Michael, NE 22990",4707209056757331019
499,lwilliams@example.org,True,SUITE,15.72,09 Sep 2020,25 Aug 2020,174.21,"732 Dale Camp\nPort Jennifer, MP 64418",213123330164875

In [8]:
from sdv.datasets.demo import get_available_demos

get_available_demos(modality='single_table')

                dataset_name  size_MB  num_tables
0                      adult    3.910           1
1                      alarm    4.520           1
2                       asia    1.280           1
3                     census   98.170           1
4            census_extended    4.950           1
5                      child    3.200           1
6                    covtype  255.650           1
7         expedia_hotel_logs    0.200           1
8             fake_companies    0.000           1
9          fake_hotel_guests    0.030           1
10                 insurance    3.340           1
11                 intrusion  162.040           1
12                      news   18.710           1
13  null_values_demo_dataset    0.274           1
14        student_placements    0.030           1
15    student_placements_pii    0.030           1

In [9]:
from sdv.datasets.demo import get_available_demos

get_available_demos(modality='single_table')

                dataset_name  size_MB  num_tables
0                      adult    3.910           1
1                      alarm    4.520           1
2                       asia    1.280           1
3                     census   98.170           1
4            census_extended    4.950           1
5                      child    3.200           1
6                    covtype  255.650           1
7         expedia_hotel_logs    0.200           1
8             fake_companies    0.000           1
9          fake_hotel_guests    0.030           1
10                 insurance    3.340           1
11                 intrusion  162.040           1
12                      news   18.710           1
13  null_values_demo_dataset    0.274           1
14        student_placements    0.030           1
15    student_placements_pii    0.030           1

In [16]:
from sdv.datasets.demo import get_available_demos

In [18]:
from sdv.datasets.demo import download_demo

In [19]:
data, metadata = download_demo(  modality='single_table',     dataset_name='adult' )

In [20]:
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,label
0,27,Private,177119,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,44,United-States,<=50K
1,27,Private,216481,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,40,United-States,<=50K
2,25,Private,256263,Assoc-acdm,12,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K
3,46,Private,147640,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,1902,40,United-States,<=50K
4,45,Private,172822,11th,7,Divorced,Transport-moving,Not-in-family,White,Male,0,2824,76,United-States,>50K

In [17]:
# See available datasets
print(get_available_demos(modality='single_table'))

                dataset_name  size_MB  num_tables
0                      adult    3.910           1
1                      alarm    4.520           1
2                       asia    1.280           1
3                     census   98.170           1
4            census_extended    4.950           1
5                      child    3.200           1
6                    covtype  255.650           1
7         expedia_hotel_logs    0.200           1
8             fake_companies    0.000           1
9          fake_hotel_guests    0.030           1
10                 insurance    3.340           1
11                 intrusion  162.040           1
12                      news   18.710           1
13  null_values_demo_dataset    0.274           1
14        student_placements    0.030           1
15    student_placements_pii    0.030           1

In [21]:
data, metadata = download_demo(  modality='single_table',     dataset_name='alarm' )
data.head()

,HISTORY,CVP,PCWP,HYPOVOLEMIA,LVEDVOLUME,LVFAILURE,STROKEVOLUME,ERRLOWOUTPUT,HRBP,HREKG,...,MINVOLSET,VENTMACH,VENTTUBE,VENTLUNG,VENTALV,ARTCO2,CATECHOL,HR,CO,BP
0,False,NORMAL,NORMAL,False,NORMAL,False,NORMAL,False,HIGH,HIGH,...,NORMAL,NORMAL,LOW,LOW,ZERO,HIGH,HIGH,HIGH,HIGH,NORMAL
1,False,HIGH,HIGH,True,HIGH,False,NORMAL,False,HIGH,NORMAL,...,NORMAL,NORMAL,LOW,LOW,ZERO,HIGH,HIGH,HIGH,HIGH,LOW
2,False,HIGH,HIGH,False,HIGH,False,NORMAL,False,LOW,LOW,...,NORMAL,NORMAL,NORMAL,HIGH,LOW,HIGH,HIGH,NORMAL,NORMAL,LOW
3,False,NORMAL,NORMAL,False,NORMAL,False,NORMAL,False,HIGH,HIGH,...,NORMAL,NORMAL,LOW,ZERO,ZERO,HIGH,HIGH,HIGH,HIGH,HIGH
4,False,NORMAL,HIGH,True,HIGH,False,NORMAL,False,HIGH,HIGH,...,HIGH,HIGH,HIGH,LOW,HIGH,LOW,HIGH,HIGH,HIGH,HIGH

In [24]:
from sdv.datasets.demo import download_demo

data, metadata = download_demo(
    modality='single_table',
    dataset_name='fake_hotel_guests'
)
data.head()

,guest_email,has_rewards,room_type,amenities_fee,checkin_date,checkout_date,room_rate,billing_address,credit_card_number
0,michaelsanders@shaw.net,False,BASIC,37.89,27 Dec 2020,29 Dec 2020,131.23,"49380 Rivers Street\nSpencerville, AK 68265",4075084747483975747
1,randy49@brown.biz,False,BASIC,24.37,30 Dec 2020,02 Jan 2021,114.43,"88394 Boyle Meadows\nConleyberg, TN 22063",180072822063468
2,webermelissa@neal.com,True,DELUXE,0.00,17 Sep 2020,18 Sep 2020,368.33,"0323 Lisa Station Apt. 208\nPort Thomas, LA 82585",38983476971380
3,gsims@terry.com,False,BASIC,NaN,28 Dec 2020,31 Dec 2020,115.61,"77 Massachusetts Ave\nCambridge, MA 02139",4969551998845740
4,misty33@smith.biz,False,BASIC,16.45,05 Apr 2020,NaN,122.41,"1234 Corporate Drive\nBoston, MA 02116",3558512986488983