# SQL - Python : Window Functions
- They are one of the most powerful SQL features because they perform calculations across related rows without collapsing the data
- A Window Function performs calculations across a set of rows (called a window) while keeping every row in the output.
- Unlike GROUP BY, window functions do not reduce the number of rows.

In [2]:
# libraries (install if required)
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [3]:
# URL-encode special chars in password if any (e.g., # -> %23, @ -> %40)  #Pass@123 - Pass%40123
engine1 = create_engine("mysql+pymysql://root:Mysql%40123@localhost:3306/piit")
# URL-encode special chars in password if any (e.g., # -> %23, @ -> %40)  #Pass@123 - Pass%40123
#engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
print(engine1)
#setting up connection mysql with user name - piuser, pwd - Pass@123 and to database piit at port no  3306

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [4]:
# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [5]:
q('show tables')

        Tables_in_piit
0               aelita
1              Authors
2                Books
3        customer_view
4            customers
5          departments
6                 dept
7              duTable
8                  emp
9            employees
10         math_scores
11              mtcars
12  order_details_view
13         order_items
14              orders
15                 pet
16  product_sales_view
17            products
18           pstudents
19               sales
20              sales1
21              sales2
22      student_scores
23      student_totals
24            students
25           students1
26           students2
27          studentsb2
28  subject_avg_scores
29              suroor

In [7]:
query1 = 'select * from emp'
emp =  pd.read_sql(query1, engine1)
query2 = 'select * from dept'
dept = pd.read_sql(query2, engine1)
print(emp.head(), '\n', dept.head())

   empno   ename       job     mgr    hiredate     sal   comm  deptno
0   1234  DHIRAJ   ANALYST  7839.0  1988-12-17  5000.0  100.0      10
1   7369   SMITH     CLERK  7902.0  1980-12-17   800.0    NaN      20
2   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0      30
3   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0  500.0      30
4   7566   JONES   MANAGER  7839.0  1981-04-02  2975.0    NaN      20
    deptno       dname       loc
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [8]:
emp

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    1234  DHIRAJ    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
2    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
3    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
4    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
5    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
6    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
7    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
8    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
9    7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
10   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
11   7876   ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
12   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
13   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
14   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

## GROUP BY vs Window Function
- Find Total Salary in each Dept : Notice that employee details disappear.

In [9]:
q3a = "select deptno, sum(sal) as TotalSalary from emp GROUP BY deptno;"
pd.read_sql(q3a, engine1)

   deptno  TotalSalary
0      10      13750.0
1      20      10875.0
2      30       9400.0

## Window Function
- Every employee remains.
- Department total is repeated.

In [11]:
q3b = "select empno, ename, deptno, sal, sum(sal) OVER (PARTITION BY deptno) AS DeptSalary from emp;"
pd.read_sql(q3b, engine1)

    empno   ename  deptno     sal  DeptSalary
0    1234  DHIRAJ      10  5000.0     13750.0
1    7782   CLARK      10  2450.0     13750.0
2    7839    KING      10  5000.0     13750.0
3    7934  MILLER      10  1300.0     13750.0
4    7369   SMITH      20   800.0     10875.0
5    7566   JONES      20  2975.0     10875.0
6    7788   SCOTT      20  3000.0     10875.0
7    7876   ADAMS      20  1100.0     10875.0
8    7902    FORD      20  3000.0     10875.0
9    7499   ALLEN      30  1600.0      9400.0
10   7521    WARD      30  1250.0      9400.0
11   7654  MARTIN      30  1250.0      9400.0
12   7698   BLAKE      30  2850.0      9400.0
13   7844  TURNER      30  1500.0      9400.0
14   7900   JAMES      30   950.0      9400.0

In [13]:
emp.assign(DeptSalary = emp.groupby('deptno', as_index=False)['sal'].transform('sum'))

,empno,ename,job,mgr,hiredate,sal,comm,deptno,DeptSalary
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,13750.0
1,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,10875.0
2,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,9400.0
3,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,9400.0
4,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,10875.0
5,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,9400.0
6,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,NaN,30,9400.0
7,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,NaN,10,13750.0
8,7788,SCOTT,ANALYST,7566.0,1987-04-19,3000.0,NaN,20,10875.0
9,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,13750.0
10,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,9400.0
11,7876,ADAMS,CLERK,7788.0,1987-05-23,1100.0,NaN,20,10875.0
12,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30,9400.0
13,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20,10875.0
14,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,13750.0

## Other Window Examples
- Show Avg Dept salary with emp details

In [15]:
q4 = "SELECT ename, deptno,  sal, AVG(sal) OVER(PARTITION BY deptno) AvgSalary FROM emp;"
pd.read_sql(q4, engine1)

     ename  deptno     sal    AvgSalary
0   DHIRAJ      10  5000.0  3437.500000
1    CLARK      10  2450.0  3437.500000
2     KING      10  5000.0  3437.500000
3   MILLER      10  1300.0  3437.500000
4    SMITH      20   800.0  2175.000000
5    JONES      20  2975.0  2175.000000
6    SCOTT      20  3000.0  2175.000000
7    ADAMS      20  1100.0  2175.000000
8     FORD      20  3000.0  2175.000000
9    ALLEN      30  1600.0  1566.666667
10    WARD      30  1250.0  1566.666667
11  MARTIN      30  1250.0  1566.666667
12   BLAKE      30  2850.0  1566.666667
13  TURNER      30  1500.0  1566.666667
14   JAMES      30   950.0  1566.666667

In [16]:
q5 = "SELECT ename, deptno,  sal, COUNT(*) OVER(PARTITION BY deptno) Employees FROM emp;"
pd.read_sql(q5, engine1)
# ename, deptno, sal, count_of_emp in same dept

     ename  deptno     sal  Employees
0   DHIRAJ      10  5000.0          4
1    CLARK      10  2450.0          4
2     KING      10  5000.0          4
3   MILLER      10  1300.0          4
4    SMITH      20   800.0          5
5    JONES      20  2975.0          5
6    SCOTT      20  3000.0          5
7    ADAMS      20  1100.0          5
8     FORD      20  3000.0          5
9    ALLEN      30  1600.0          6
10    WARD      30  1250.0          6
11  MARTIN      30  1250.0          6
12   BLAKE      30  2850.0          6
13  TURNER      30  1500.0          6
14   JAMES      30   950.0          6

In [18]:
emp.groupby('deptno').agg({"ename":'count'}).reset_index()

   deptno  ename
0      10      4
1      20      5
2      30      6

In [20]:
q6 = "SELECT ename, deptno,  sal, MAX(sal) OVER(PARTITION BY deptno) MaxSalary FROM emp;"
pd.read_sql(q6, engine1)

     ename  deptno     sal  MaxSalary
0   DHIRAJ      10  5000.0     5000.0
1    CLARK      10  2450.0     5000.0
2     KING      10  5000.0     5000.0
3   MILLER      10  1300.0     5000.0
4    SMITH      20   800.0     3000.0
5    JONES      20  2975.0     3000.0
6    SCOTT      20  3000.0     3000.0
7    ADAMS      20  1100.0     3000.0
8     FORD      20  3000.0     3000.0
9    ALLEN      30  1600.0     2850.0
10    WARD      30  1250.0     2850.0
11  MARTIN      30  1250.0     2850.0
12   BLAKE      30  2850.0     2850.0
13  TURNER      30  1500.0     2850.0
14   JAMES      30   950.0     2850.0

In [21]:
q7 = "SELECT ename, deptno,  sal, ROW_NUMBER() OVER(PARTITION BY deptno ORDER BY sal DESC) as RowNo FROM emp;"
pd.read_sql(q7, engine1)

     ename  deptno     sal  RowNo
0   DHIRAJ      10  5000.0      1
1     KING      10  5000.0      2
2    CLARK      10  2450.0      3
3   MILLER      10  1300.0      4
4    SCOTT      20  3000.0      1
5     FORD      20  3000.0      2
6    JONES      20  2975.0      3
7    ADAMS      20  1100.0      4
8    SMITH      20   800.0      5
9    BLAKE      30  2850.0      1
10   ALLEN      30  1600.0      2
11  TURNER      30  1500.0      3
12    WARD      30  1250.0      4
13  MARTIN      30  1250.0      5
14   JAMES      30   950.0      6

In [22]:
empDeptSal = emp.sort_values(by=['deptno','sal'], ascending =[True,False])
empDeptSal

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    1234  DHIRAJ    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
9    7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
7    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
14   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10
8    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
13   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
4    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
11   7876   ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
1    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
6    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
2    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
10   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
3    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
5    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
12   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30

In [23]:
empDeptSal.sort_values(by=['deptno','sal'], ascending =[True,False]).assign(RowNo=empDeptSal.groupby('deptno').cumcount() + 1)

,empno,ename,job,mgr,hiredate,sal,comm,deptno,RowNo
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,1
9,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,2
7,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,NaN,10,3
14,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,4
8,7788,SCOTT,ANALYST,7566.0,1987-04-19,3000.0,NaN,20,1
13,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20,2
4,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,3
11,7876,ADAMS,CLERK,7788.0,1987-05-23,1100.0,NaN,20,4
1,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,5
6,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,NaN,30,1
2,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,2
10,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,3
3,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,4
5,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,5
12,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30,6

In [ ]:
# Ranking Notice rank 2 may skipped.
q8 = "SELECT ename, deptno,  sal, RANK() OVER(PARTITION BY deptno ORDER BY sal DESC) RankNo FROM emp;"
pd.read_sql(q8, engine1)

In [ ]:
q9= " SELECT ename,  deptno, sal,  LAST_VALUE(ename)   OVER(  PARTITION BY deptno ORDER BY \
sal DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING  ) LowestPaid FROM emp;"
pd.read_sql(q9, engine1)

## Multiple CTEs

In [ ]:
q11 = "WITH DeptSalary AS (SELECT deptno, SUM(sal) TotalSalary FROM emp GROUP BY deptno), \
 DeptAvg AS ( SELECT deptno, AVG(sal) AvgSalary FROM emp GROUP BY deptno ) \
 SELECT s.deptno,  s.TotalSalary, a.AvgSalary FROM DeptSalary s  JOIN DeptAvg a ON s.deptno=a.deptno;"
pd.read_sql(q11, engine1)

In [ ]:
emp.groupby('deptno').agg({'sal':['sum', 'mean','max']}).reset_index().round()

In [ ]:
emp.groupby('deptno').agg( TotalSalary=('sal', 'sum'), AvgSalary=('sal', 'mean'), MaxSalary=('sal', 'max')).reset_index()

# Highest paid employee in each department.
q10 = " ;"
pd.read_sql(q10, engine1)

# A simple rule for students
* GROUP BY summarizes data, so you lose the individual employee rows.
* Window functions keep every employee row and add information such as department totals, averages, ranks, running totals, or previous/next values.
* Think of the OVER() clause as saying: “Perform this calculation over a window of related rows, but don’t collapse the result into a summary.”

## CTE functions 
- A CTE (Common Table Expression) is a temporary named result set that exists only for the duration of a single SQL statement. It makes complex queries much easier to read and maintain.
- Think of it as a temporary table created inside a query.
- CTEs are easier to understand and can be reused within the same query.

In [24]:
## Without CTE
c1 = "SELECT deptno, AVG(sal) FROM( SELECT deptno, sal FROM emp  WHERE sal > 1000) t GROUP BY deptno;"
pd.read_sql(c1, engine1)

   deptno  AVG(sal)
0      10   3437.50
1      20   2518.75
2      30   1690.00

In [25]:
c2 = "WITH EmpData AS ( SELECT deptno, sal FROM emp WHERE sal > 1000) SELECT deptno,  AVG(sal) FROM EmpData GROUP BY deptno;"
pd.read_sql(c2, engine1)

   deptno  AVG(sal)
0      10   3437.50
1      20   2518.75
2      30   1690.00

In [26]:
emp.groupby('deptno').agg({'sal':'mean'}).reset_index()

   deptno          sal
0      10  3437.500000
1      20  2175.000000
2      30  1566.666667

In [ ]:
c3 = " WITH RECURSIVE EmployeeTree AS ( SELECT empno,   ename,  mgr, 1 AS Level FROM emp WHERE mgr IS NULL \
UNION ALL SELECT e.empno,  e.ename,  e.mgr,  Level+1 FROM emp e JOIN EmployeeTree t ON e.mgr=t.empno ) SELECT * FROM EmployeeTree;"
pd.read_sql(c3, engine1)

In [ ]:
## Sub Query * CTE
c5a = "SELECT * FROM ( SELECT deptno,  SUM(sal) TotalSalary FROM emp GROUP BY deptno) t";
pd.read_sql(c5a, engine1)

In [ ]:
c5b = "WITH DeptSalary AS ( SELECT deptno,  SUM(sal) TotalSalary FROM emp GROUP BY deptno ) SELECT * FROM DeptSalary;"
pd.read_sql(c5b, engine1)

* Subquery = A calculation written inside another query.
* CTE = Give that calculation a name and reuse it.
* View = Save that named query permanently in the database.
* Window Function = Perform calculations across related rows while keeping every row in the result.