# Cheat sheets

## https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

In [1]:
import pandas as pd
from pydataset import data
import matplotlib.pyplot as plt

### Creating DF

In [3]:
df1 = pd.DataFrame(
 {"a" : [4, 5, 6],
 "b" : [7, 8, 9],
 "c" : [10, 11, 12]},
 index = [1, 2, 3])
df1

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [4]:
df2 = pd.DataFrame(
 [[4, 7, 10],
 [5, 8, 11],
 [6, 9, 12]],
 index=[1, 2, 3],
 columns=['a', 'b', 'c'])
df2

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [5]:
df3 = pd.DataFrame(
 {"a" : [4 ,5, 6],
 "b" : [7, 8, 9],
 "c" : [10, 11, 12]},
index = pd.MultiIndex.from_tuples(
 [('d', 1), ('d', 2),
 ('e', 2)], names=['n', 'v']))
df3

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

## Method Chaining
- df = (pd.melt(df).rename(columns={ 'variable':'var',  'value':'val'}).query('val >= 200')  )

In [8]:
pd.melt(df1)

  variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [9]:
df1b = (pd.melt(df1).rename(columns={ 'variable':'cat',  'value':'x'}).query('x >= 7')  )
df1b

  cat   x
3   b   7
4   b   8
5   b   9
6   c  10
7   c  11
8   c  12

## Reshape Data

In [10]:
pd.melt(df1)

  variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [15]:
df1b.pivot(columns='cat', values='x')

cat    b     c
3    7.0   NaN
4    8.0   NaN
5    9.0   NaN
6    NaN  10.0
7    NaN  11.0
8    NaN  12.0

In [16]:
mtcars = data('mtcars')
mtcars

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [18]:
mtcars.sort_values('mpg').head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4

In [19]:
mtcars.sort_values('mpg', ascending=False).head()

                 mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  carb
Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1     4     1
Fiat 128        32.4    4  78.7   66  4.08  2.200  19.47   1   1     4     1
Lotus Europa    30.4    4  95.1  113  3.77  1.513  16.90   1   1     5     2
Honda Civic     30.4    4  75.7   52  4.93  1.615  18.52   1   1     4     2
Fiat X1-9       27.3    4  79.0   66  4.08  1.935  18.90   1   1     4     1

In [25]:
mtcars.sort_values(['gear','mpg']).head().loc[:, ['gear', 'mpg']]

                     gear   mpg
Cadillac Fleetwood      3  10.4
Lincoln Continental     3  10.4
Camaro Z28              3  13.3
Duster 360              3  14.3
Chrysler Imperial       3  14.7

In [27]:
mtcars.rename(columns = {'am':'Transmission'}).head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,Transmission,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [29]:
mtcars.sort_index().head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1

In [32]:
mtcars.drop(columns = ['am','mpg'], axis=1).head()

                   cyl   disp   hp  drat     wt   qsec  vs  gear  carb
Mazda RX4            6  160.0  110  3.90  2.620  16.46   0     4     4
Mazda RX4 Wag        6  160.0  110  3.90  2.875  17.02   0     4     4
Datsun 710           4  108.0   93  3.85  2.320  18.61   1     4     1
Hornet 4 Drive       6  258.0  110  3.08  3.215  19.44   1     3     1
Hornet Sportabout    8  360.0  175  3.15  3.440  17.02   0     3     2

## Subset Obsvervations - rows

In [34]:
mtcars[mtcars.mpg > 30].head()

                 mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  carb
Fiat 128        32.4    4  78.7   66  4.08  2.200  19.47   1   1     4     1
Honda Civic     30.4    4  75.7   52  4.93  1.615  18.52   1   1     4     2
Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1     4     1
Lotus Europa    30.4    4  95.1  113  3.77  1.513  16.90   1   1     5     2

In [39]:
mtcars[['am','cyl']].drop_duplicates()

                   am  cyl
Mazda RX4           1    6
Datsun 710          1    4
Hornet 4 Drive      0    6
Hornet Sportabout   0    8
Merc 240D           0    4
Ford Pantera L      1    8

In [40]:
mtcars.sample(frac=.5)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1

In [47]:
mtcars.nlargest(5,'mpg')

                 mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  carb
Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1     4     1
Fiat 128        32.4    4  78.7   66  4.08  2.200  19.47   1   1     4     1
Honda Civic     30.4    4  75.7   52  4.93  1.615  18.52   1   1     4     2
Lotus Europa    30.4    4  95.1  113  3.77  1.513  16.90   1   1     5     2
Fiat X1-9       27.3    4  79.0   66  4.08  1.935  18.90   1   1     4     1

In [45]:
mtcars.nlargest(5,'wt')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2

In [49]:
mtcars.nlargest(5,['mpg','wt'])

                 mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  carb
Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1     4     1
Fiat 128        32.4    4  78.7   66  4.08  2.200  19.47   1   1     4     1
Honda Civic     30.4    4  75.7   52  4.93  1.615  18.52   1   1     4     2
Lotus Europa    30.4    4  95.1  113  3.77  1.513  16.90   1   1     5     2
Fiat X1-9       27.3    4  79.0   66  4.08  1.935  18.90   1   1     4     1

In [50]:
mtcars.head(2)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

In [51]:
mtcars.tail(3)

                mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
Ferrari Dino   19.7    6  145.0  175  3.62  2.77  15.5   0   1     5     6
Maserati Bora  15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8
Volvo 142E     21.4    4  121.0  109  4.11  2.78  18.6   1   1     4     2

In [53]:
pd.concat([mtcars.head(3), mtcars.tail(3)])

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Ferrari Dino   19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
Volvo 142E     21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [60]:
mtcars.query('mpg >30')

                 mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  carb
Fiat 128        32.4    4  78.7   66  4.08  2.200  19.47   1   1     4     1
Honda Civic     30.4    4  75.7   52  4.93  1.615  18.52   1   1     4     2
Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1     4     1
Lotus Europa    30.4    4  95.1  113  3.77  1.513  16.90   1   1     5     2

In [62]:
mtcars.query('mpg >30 & gear == 4')

                 mpg  cyl  disp  hp  drat     wt   qsec  vs  am  gear  carb
Fiat 128        32.4    4  78.7  66  4.08  2.200  19.47   1   1     4     1
Honda Civic     30.4    4  75.7  52  4.93  1.615  18.52   1   1     4     2
Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.90   1   1     4     1

In [73]:
mtcars.reset_index().head()

,index,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [76]:
mtcars.reset_index().query('index.str.startswith("Ma")', engine="python")

,index,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

## Subset Columns

In [56]:
mtcars[['mpg','hp','am']].head()

                    mpg   hp  am
Mazda RX4          21.0  110   1
Mazda RX4 Wag      21.0  110   1
Datsun 710         22.8   93   1
Hornet 4 Drive     21.4  110   0
Hornet Sportabout  18.7  175   0

In [57]:
mtcars.mpg.head()

Mazda RX4            21.0
Mazda RX4 Wag        21.0
Datsun 710           22.8
Hornet 4 Drive       21.4
Hornet Sportabout    18.7
Name: mpg, dtype: float64

In [59]:
mtcars.filter(regex='m').head() # cols having m in their names

                    mpg  am
Mazda RX4          21.0   1
Mazda RX4 Wag      21.0   1
Datsun 710         22.8   1
Hornet 4 Drive     21.4   0
Hornet Sportabout  18.7   0

## Subset Rows and Columns
- Use df.loc[] and df.iloc[] to select only rows, only columns or both.
- Use df.at[] and df.iat[] to access a single value by row and column.
- First index selects rows, second index columns.

In [78]:
mtcars.iloc[10:15]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Merc 280C,17.8,6,167.6,123,3.92,3.44,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.07,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.73,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.78,18.00,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.25,17.98,0,0,3,4

In [80]:
mtcars.iloc[:,[1,2,5]].head()

                   cyl   disp     wt
Mazda RX4            6  160.0  2.620
Mazda RX4 Wag        6  160.0  2.875
Datsun 710           4  108.0  2.320
Hornet 4 Drive       6  258.0  3.215
Hornet Sportabout    8  360.0  3.440

In [84]:
mtcars.loc[:, 'mpg':'wt'].head()  #names of columns

                    mpg  cyl   disp   hp  drat     wt
Mazda RX4          21.0    6  160.0  110  3.90  2.620
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875
Datsun 710         22.8    4  108.0   93  3.85  2.320
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440

In [85]:
mtcars.loc[:, ['mpg','wt','am']].head()

                    mpg     wt  am
Mazda RX4          21.0  2.620   1
Mazda RX4 Wag      21.0  2.875   1
Datsun 710         22.8  2.320   1
Hornet 4 Drive     21.4  3.215   0
Hornet Sportabout  18.7  3.440   0

In [86]:
mtcars.loc[mtcars['mpg'] > 30, ['mpg','wt','am']].head()

                 mpg     wt  am
Fiat 128        32.4  2.200   1
Honda Civic     30.4  1.615   1
Toyota Corolla  33.9  1.835   1
Lotus Europa    30.4  1.513   1

In [91]:
mtcars.iat[1,2]  # by index

np.float64(160.0)

In [90]:
mtcars.at['Fiat 128','am']  #by  label

np.int64(1)

## Logic

In [96]:
mtcars.cyl.isin(values = [2,4,7])

Mazda RX4              False
Mazda RX4 Wag          False
Datsun 710              True
Hornet 4 Drive         False
Hornet Sportabout      False
Valiant                False
Duster 360             False
Merc 240D               True
Merc 230                True
Merc 280               False
Merc 280C              False
Merc 450SE             False
Merc 450SL             False
Merc 450SLC            False
Cadillac Fleetwood     False
Lincoln Continental    False
Chrysler Imperial      False
Fiat 128                True
Honda Civic             True
Toyota Corolla          True
Toyota Corona           True
Dodge Challenger       False
AMC Javelin            False
Camaro Z28             False
Pontiac Firebird       False
Fiat X1-9               True
Porsche 914-2           True
Lotus Europa            True
Ford Pantera L         False
Ferrari Dino           False
Maserati Bora          False
Volvo 142E              True
Name: cyl, dtype: bool