### Pandas
- https://pandas.pydata.org/
- library or set of modules available for data manipulation
- is an open-source Python library used for data manipulation and analysis. It provides high-performance, easy-to-use data structures designed to work with "relational" or "labeled" data, such as tables and time series.
- a library is a reusable collection of pre-written code that allows developers to perform specific tasks without writing everything from scratch. These collections typically consist of multiple related modules and packages grouped under a single name.

In [4]:
import pandas as pd  #pd is an alias for pandas
# loading a library is done using the import statement. Before a library can be loaded (imported), it must be installed on your system if it is not already part of the Python Standard Library.

In [ ]:
pd.  #tab to see functions of pandas

In [ ]:
# Set Pandas options for wrapping
pd.set_option('display.max_columns', None)   # Show all columns
pd.set_option('display.width', 100)          # Set line width before wrapping
pd.set_option('display.max_colwidth', None)  # Don't truncate text

In [ ]:
#pip install pydataset # install pydataset library

In [6]:
from pydataset import data  #load library of pydataset and import mtcars data from it
#https://pydataset.readthedocs.io/en/latest/
mtcars = data('mtcars')
mtcars.head(4)

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710      22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1

In [15]:
#help(mtcars.head())

In [19]:
mtcars[0:10:3]

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Duster 360      14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
Merc 280        19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4

In [20]:
type(mtcars)

pandas.core.frame.DataFrame

In [ ]:
#pd.Dat # after dot(.) press tab to get functions

In [22]:
#?pd.DataFrame.head

In [23]:
#help(pd.DataFrame.head)

In [24]:
mtcars.head(n=3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

## Functions in Pandas
- Understanding Data
    - type  # type of object
    - shape # rows & cols in data
    - columns # column names
    - dtypes  # datatype 
    - info()  # datatypes & non-null counts
    - sample(x) # randon x rows
    - head(x) # first x rows
    - tail(x) # last x rows
- Summary Statistics
    - describe()  #summary stats for numeric cols
    - describe(include='all')  #summary stats for all cols
    - mtcars.nunique() #count of unique values per column
    - value_counts()  # freq count for a series
- Missing/Duplicates
    -  isnull().sum()   # missing value count per cols
    -  notnull().sum()  # non missing value count
    -  duplicated(().sum() # count of duplicate rows
- View Specific Col/ Row
    -  ['col_name']   # single column
    -  [['col1','col2']] # multiple columns
    -  iloc[0]   #1st row by index position
    -  loc[0] #1st row by label
    -  iloc[0:5]   # first 5 rows
-  Basic Data Insights
    -  corr(numeric_only=True)  #correlation matrix (numeric only)
    -  mean(numeric_only=True)   #mean of numeric cols
    -  mode().iloc(0) #most frequent values
    -  median(numeric_only=True) # median of numeric cols

In [25]:
type(mtcars)  #type of object

pandas.core.frame.DataFrame

In [26]:
mtcars.head() #first 5 rows of mtcars data set  (which is impported from pydataset library)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [27]:
mtcars.tail(4) #Last 4 rows from mtcars dataset

                 mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
Ford Pantera L  15.8    8  351.0  264  4.22  3.17  14.5   0   1     5     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.77  15.5   0   1     5     6
Maserati Bora   15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8
Volvo 142E      21.4    4  121.0  109  4.11  2.78  18.6   1   1     4     2

In [28]:
mtcars.sample(3)  #any 3 row on sampling / random

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Volvo 142E      21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2
Duster 360      14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1

In [29]:
mtcars.shape #rows , columns - structure

(32, 11)

In [30]:
mtcars.columns # title, names of columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='object')

In [31]:
mtcars.info() # info about dataset, every col - non-null , data type; float -  decimal; int- without decimal; 64 - bit
#10020202020.222

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64
 8   am      32 non-null     int64
 9   gear    32 non-null     int64
 10  carb    32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 3.0+ KB

In [32]:
mtcars.dtypes #column names and types

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [33]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='object')

In [34]:
mtcars.head(2)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

## Summary

In [35]:
mtcars.describe() #for all numeric cols - count, min, max, mean, std dev, Q1, Q2, Q3

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [36]:
mtcars.mpg.describe()

count    32.000000
mean     20.090625
std       6.026948
min      10.400000
25%      15.425000
50%      19.200000
75%      22.800000
max      33.900000
Name: mpg, dtype: float64

In [37]:
mtcars.describe(include='all')  #for all types of columns

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [38]:
mtcars.cyl.value_counts() # count of each cyl type cars

cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [39]:
mtcars.nunique()   # count of unique values in each col

mpg     25
cyl      3
disp    27
hp      22
drat    22
wt      29
qsec    30
vs       2
am       2
gear     3
carb     6
dtype: int64

In [40]:
mtcars.gear.value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [41]:
mtcars['am'].value_counts()  #by tx

am
0    19
1    13
Name: count, dtype: int64

## Read/ Write - CSV/ EXCEL
-

## Read/write to CSV

In [42]:
mtcars.to_csv('mtcarsdata.csv', index=False)

In [ ]:
mtcars2 = pd.read_csv('mtcarsdata.csv')
mtcars2.head(2)

## read/write to Excel
- https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html

In [ ]:
#?mtcars.to_excel

In [ ]:
mtcars.to_excel('mtcarsdata2.xlsx', index=False)
# index - rownames get stored if index -T

In [ ]:
mtcars3 = pd.read_excel('mtcarsdata2.xlsx', sheet_name=0)
mtcars3.head(5)

In [ ]:
#mtcars.to_excel('mtcarsdata2.xlsx', index=True) - same mtcars.to_excel('mtcarsdata2.xlsx')

## Missing
- df.isnull() - missing values
- https://pandas.pydata.org/docs/reference/api/pandas.isnull.html
- df.notnull()  - not null values

In [43]:
mtcars.shape  #rows, cols

(32, 11)

In [45]:
mtcars.isnull()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,False,False,False,False,False,False,False,False,False,False,False
Mazda RX4 Wag,False,False,False,False,False,False,False,False,False,False,False
Datsun 710,False,False,False,False,False,False,False,False,False,False,False
Hornet 4 Drive,False,False,False,False,False,False,False,False,False,False,False
Hornet Sportabout,False,False,False,False,False,False,False,False,False,False,False
Valiant,False,False,False,False,False,False,False,False,False,False,False
Duster 360,False,False,False,False,False,False,False,False,False,False,False
Merc 240D,False,False,False,False,False,False,False,False,False,False,False
Merc 230,False,False,False,False,False,False,False,False,False,False,False
Merc 280,False,False,False,False,False,False,False,False,False,False,False
Merc 280C,False,False,False,False,False,False,False,False,False,False,False
Merc 450SE,False,False,False,False,False,False,False,False,False,False,False
Merc 450SL,False,False,False,False,False,False,False,False,False,False,False
Merc 450SLC,False,False,False,False,False,False,False,False,False,False,False
Cadillac Fleetwood,False,False,False,False,False,False,False,False,False,False,False
Lincoln Continental,False,False,False,False,False,False,False,False,False,False,False
Chrysler Imperial,False,False,False,False,False,False,False,False,False,False,False
Fiat 128,False,False,False,False,False,False,False,False,False,False,False
Honda Civic,False,False,False,False,False,False,False,False,False,False,False
Toyota Corolla,False,False,False,False,False,False,False,False,False,False,False
Toyota Corona,False,False,False,False,False,False,False,False,False,False,False
Dodge Challenger,False,False,False,False,False,False,False,False,False,False,False
AMC Javelin,False,False,False,False,False,False,False,False,False,False,False
Camaro Z28,False,False,False,False,False,False,False,False,False,False,False
Pontiac Firebird,False,False,False,False,False,False,False,False,False,False,False
Fiat X1-9,False,False,False,False,False,False,False,False,False,False,False
Porsche 914-2,False,False,False,False,False,False,False,False,False,False,False
Lotus Europa,False,False,False,False,False,False,False,False,False,False,False
Ford Pantera L,False,False,False,False,False,False,False,False,False,False,False
Ferrari Dino,False,False,False,False,False,False,False,False,False,False,False
Maserati Bora,False,False,False,False,False,False,False,False,False,False,False
Volvo 142E,False,False,False,False,False,False,False,False,False,False,False

In [46]:
mtcars.isnull().sum().sum() # missing values in full Data Frame

np.int64(0)

In [47]:
mtcars.isnull().head()  # False -> 0, True - 1

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,False,False,False,False,False,False,False,False,False,False,False
Mazda RX4 Wag,False,False,False,False,False,False,False,False,False,False,False
Datsun 710,False,False,False,False,False,False,False,False,False,False,False
Hornet 4 Drive,False,False,False,False,False,False,False,False,False,False,False
Hornet Sportabout,False,False,False,False,False,False,False,False,False,False,False

In [48]:
mtcars.isnull().sum(axis=0)  #counting missing values, columns wise, axis=0 (Columns)

mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

In [49]:
mtcars.isnull().sum(axis=1)  # count missing values, rowwise , axis=1 (Rows)

Mazda RX4              0
Mazda RX4 Wag          0
Datsun 710             0
Hornet 4 Drive         0
Hornet Sportabout      0
Valiant                0
Duster 360             0
Merc 240D              0
Merc 230               0
Merc 280               0
Merc 280C              0
Merc 450SE             0
Merc 450SL             0
Merc 450SLC            0
Cadillac Fleetwood     0
Lincoln Continental    0
Chrysler Imperial      0
Fiat 128               0
Honda Civic            0
Toyota Corolla         0
Toyota Corona          0
Dodge Challenger       0
AMC Javelin            0
Camaro Z28             0
Pontiac Firebird       0
Fiat X1-9              0
Porsche 914-2          0
Lotus Europa           0
Ford Pantera L         0
Ferrari Dino           0
Maserati Bora          0
Volvo 142E             0
dtype: int64

In [ ]:
# Opposite of isnull or notnull
mtcars.notnull().sum(axis=0) # for each column, count non-missing values, 32

In [52]:
mtcars.sum(axis=0)

mpg      642.900
cyl      198.000
disp    7383.100
hp      4694.000
drat     115.090
wt       102.952
qsec     571.160
vs        14.000
am        13.000
gear     118.000
carb      90.000
dtype: float64

In [53]:
mtcars.sum(axis=1)

Mazda RX4              328.980
Mazda RX4 Wag          329.795
Datsun 710             259.580
Hornet 4 Drive         426.135
Hornet Sportabout      590.310
Valiant                385.540
Duster 360             656.920
Merc 240D              270.980
Merc 230               299.570
Merc 280               350.460
Merc 280C              349.660
Merc 450SE             510.740
Merc 450SL             511.500
Merc 450SLC            509.850
Cadillac Fleetwood     728.560
Lincoln Continental    726.644
Chrysler Imperial      725.695
Fiat 128               213.850
Honda Civic            195.165
Toyota Corolla         206.955
Toyota Corona          273.775
Dodge Challenger       519.650
AMC Javelin            506.085
Camaro Z28             646.280
Pontiac Firebird       631.175
Fiat X1-9              208.215
Porsche 914-2          272.570
Lotus Europa           273.683
Ford Pantera L         670.690
Ferrari Dino           379.590
Maserati Bora          694.710
Volvo 142E             288.890
dtype: float64

In [ ]:
mtcars.notnull().sum(axis=1)  # for each row, count of non-missing values, 11

In [54]:
32 * 11

352

In [57]:
mtcars.notnull().sum(axis=0).sum()

np.int64(352)

In [ ]:
mtcars.head()

In [58]:
mtcars.max(axis=0)

mpg      33.900
cyl       8.000
disp    472.000
hp      335.000
drat      4.930
wt        5.424
qsec     22.900
vs        1.000
am        1.000
gear      5.000
carb      8.000
dtype: float64

In [ ]:
mtcars.notnull().sum(axis=0).sum() # 32 x 11

# Check for Duplicates
- duplicated()  #check for duplicate rows
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html

In [ ]:
#?mtcars.duplicated
mtcars = data('mtcars')
mtcars.head(2)

In [ ]:
mtcars2 = mtcars.copy().reset_index().rename(columns={'index':'car'})  #duplicate, reset_index (rownames to column by index), rename by index to car
mtcars2.head()

In [ ]:
mtcars2.shape   #car - 12

### simulate duplicate rows

In [ ]:
mtcars2[mtcars2['car'] == 'Mazda RX4']  #all cars with name of Mazda RX4

In [ ]:
mazda2 = mtcars2[mtcars2['car'] == 'Mazda RX4']
datson2 = mtcars2[mtcars2['car'] == 'Datsun 710']
# copied mazda and datson car in variable/ row

In [ ]:
mtcars_dup = pd.concat([mtcars2, mazda2, datson2, mazda2], ignore_index=True) # 2 more cars Mazda, 1 more car for Datson
mtcars_dup #.sort_values('car')

In [ ]:
mtcars_dup.shape

In [ ]:
mtcars_dup[mtcars_dup['car'] == 'Mazda RX4']
#duplicate cars - 3 cars of Mazda RX4

In [ ]:
mtcars_dup[mtcars_dup['car'] == 'Datsun 710']

In [ ]:
mtcars_dup.duplicated().sum()  #duplicate rows - 3

In [ ]:
#mtcars_dup.duplicated(subset = ['gear']).sum()

In [ ]:
#mtcars_dup.duplicated(keep=False)  #mark all duplicates

In [ ]:
mtcars_dup.drop_duplicates()

In [ ]:
#?mtcars_dup.drop_duplicates

In [ ]:
mtcars_dup.drop_duplicates(keep='first')  #first

In [ ]:
mtcars_dup.drop_duplicates(keep='last')

In [ ]:
mtcars_dup.drop_duplicates(keep=False)  #remove duplicates

In [ ]:
mtcars_dup[mtcars_dup.duplicated(subset = ['vs','am','gear','carb'])].sort_values(['vs','am','gear','carb'])

In [ ]:
mtcars[mtcars.duplicated(subset = ['gear','am','cyl','carb'], keep=False)].sort_values(by=['gear','am','cyl','carb'])
#keep=False marks all occurrences of duplicates, not just the later ones.

In [ ]:
mtcars_dup[~ mtcars_dup.duplicated(subset = ['gear','am','cyl','carb'], keep=False)].sort_values(by=['gear','am','cyl','carb'])
# non duplicates wrt column in subjset

In [ ]:
mtcars_dup.drop_duplicates(subset = ['gear','am','cyl','carb'], inplace=False)
#remove duplicates by selected columns

### View rows/ columns

In [59]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [60]:
mtcars['mpg'].head()

Mazda RX4            21.0
Mazda RX4 Wag        21.0
Datsun 710           22.8
Hornet 4 Drive       21.4
Hornet Sportabout    18.7
Name: mpg, dtype: float64

In [61]:
mtcars.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='object')

In [64]:
mtcars[['wt','cyl','mpg','gear']].tail()

                   wt  cyl   mpg  gear
Lotus Europa    1.513    4  30.4     5
Ford Pantera L  3.170    8  15.8     5
Ferrari Dino    2.770    6  19.7     5
Maserati Bora   3.570    8  15.0     5
Volvo 142E      2.780    4  21.4     4

In [65]:
mtcars.iloc[0] #1st row

mpg      21.00
cyl       6.00
disp    160.00
hp      110.00
drat      3.90
wt        2.62
qsec     16.46
vs        0.00
am        1.00
gear      4.00
carb      4.00
Name: Mazda RX4, dtype: float64

In [66]:
mtcars.iloc[3:5]  #3rd to 5th row, all columns

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [67]:
mtcars.iloc[[0,4]]  #index position

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.62,16.46,0,1,4,4
Hornet Sportabout,18.7,8,360.0,175,3.15,3.44,17.02,0,0,3,2

In [68]:
mtcars.iloc[0:4]  # range of index position,   x:y  : from x to y-1

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710      22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1

In [ ]:
mtcars.head(5)

In [69]:
mtcars.loc['Datsun 710']  #row by rowname

mpg      22.80
cyl       4.00
disp    108.00
hp       93.00
drat      3.85
wt        2.32
qsec     18.61
vs        1.00
am        1.00
gear      4.00
carb      1.00
Name: Datsun 710, dtype: float64

In [70]:
carlist = ['Mazda RX4','Datsun 710']
#mtcars.loc[['Mazda RX4','Datsun 710']] #row by rowname
mtcars.loc[carlist]

             mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
Mazda RX4   21.0    6  160.0  110  3.90  2.62  16.46   0   1     4     4
Datsun 710  22.8    4  108.0   93  3.85  2.32  18.61   1   1     4     1

In [71]:
mtcars.iloc[[0,2]]

             mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
Mazda RX4   21.0    6  160.0  110  3.90  2.62  16.46   0   1     4     4
Datsun 710  22.8    4  108.0   93  3.85  2.32  18.61   1   1     4     1

In [ ]:
mtcars.columns

In [73]:
mtcars.loc[:, 'mpg':'wt'] # from mpg to wt columns by name

                      mpg  cyl   disp   hp  drat     wt
Mazda RX4            21.0    6  160.0  110  3.90  2.620
Mazda RX4 Wag        21.0    6  160.0  110  3.90  2.875
Datsun 710           22.8    4  108.0   93  3.85  2.320
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440
Valiant              18.1    6  225.0  105  2.76  3.460
Duster 360           14.3    8  360.0  245  3.21  3.570
Merc 240D            24.4    4  146.7   62  3.69  3.190
Merc 230             22.8    4  140.8   95  3.92  3.150
Merc 280             19.2    6  167.6  123  3.92  3.440
Merc 280C            17.8    6  167.6  123  3.92  3.440
Merc 450SE           16.4    8  275.8  180  3.07  4.070
Merc 450SL           17.3    8  275.8  180  3.07  3.730
Merc 450SLC          15.2    8  275.8  180  3.07  3.780
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250
Lincoln Continental  10.4    8  460.0  215  3.00  5.424
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345
Fiat 128             32.4    4   78.7   66  4.08  2.200
Honda Civic          30.4    4   75.7   52  4.93  1.615
Toyota Corolla       33.9    4   71.1   65  4.22  1.835
Toyota Corona        21.5    4  120.1   97  3.70  2.465
Dodge Challenger     15.5    8  318.0  150  2.76  3.520
AMC Javelin          15.2    8  304.0  150  3.15  3.435
Camaro Z28           13.3    8  350.0  245  3.73  3.840
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845
Fiat X1-9            27.3    4   79.0   66  4.08  1.935
Porsche 914-2        26.0    4  120.3   91  4.43  2.140
Lotus Europa         30.4    4   95.1  113  3.77  1.513
Ford Pantera L       15.8    8  351.0  264  4.22  3.170
Ferrari Dino         19.7    6  145.0  175  3.62  2.770
Maserati Bora        15.0    8  301.0  335  3.54  3.570
Volvo 142E           21.4    4  121.0  109  4.11  2.780

In [74]:
mandalCarList = ['Mazda RX4','Datsun 710', 'Hornet 4 Drive']  #list of cars
print(mandalCarList)
mtcars.loc[mandalCarList, 'mpg':'wt'].head()  # row by names, col by names

['Mazda RX4', 'Datsun 710', 'Hornet 4 Drive']

                 mpg  cyl   disp   hp  drat     wt
Mazda RX4       21.0    6  160.0  110  3.90  2.620
Datsun 710      22.8    4  108.0   93  3.85  2.320
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215

In [75]:
mtcars.loc[['Mazda RX4','Datsun 710', 'Hornet 4 Drive'], 'mpg':'wt'].head()

                 mpg  cyl   disp   hp  drat     wt
Mazda RX4       21.0    6  160.0  110  3.90  2.620
Datsun 710      22.8    4  108.0   93  3.85  2.320
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215

In [ ]:
mtcars.index

In [ ]:
mtcars.iloc[:, 3:8].head()

In [ ]:
mtcars.iloc[1:10, [3,6,9,10]] #.head()  #4th, 7th, 10th, 11th col

In [ ]:
mtcars.iloc[0:3, [3,6,9,10]]

In [ ]:
mtcars.iloc[[0,4,31], [3,6,9,10]].head()  #4th, 7th, 10th, 11th col with 1st, 5th, 32th row

In [ ]:
mtcars.columns

## Summmary
- iloc - locating an item by index
- missing value - isnull, notnull
- duplicate - locating, remove
- Read/ Write to CSV, Excel  : df.to_csv, pd.read_csv  . excel
- filter specific columns or rows
- items in columns - concate - rows
- shape, head, tail, columns, str, help, ?
- import data from pydataset
- range

## END HERE
- Go To Advanced
- Mandal & Suroor - help students with GitHub, Anaconda, *
- Asssignment, Task