# Tableau Groups & Sets
- Group - Manual
- Sets - Based on Condition
    - https://help.tableau.com/current/pro/desktop/en-us/sortgroup_sets_create.htm
    -  
- https://help.tableau.com/current/pro/desktop/en-us/sortgroup_groups_creating.htm
- https://help.tableau.com/current/pro/desktop/en-us/sortgroup_groups_creating.htm

## Python Groups and Sets
### Groups

In [16]:
# Data
import numpy as np
import pandas as pd
import datetime as dt
import plotly.express as px
url1 = 'https://raw.githubusercontent.com/dupadhyaya/piit/refs/heads/main/data/superstore_orders.csv'
print(url1)
sales = pd.read_csv(url1)
sales.shape

https://raw.githubusercontent.com/dupadhyaya/piit/refs/heads/main/data/superstore_orders.csv

(10194, 21)

In [17]:
sales.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [18]:
sales=sales.rename(columns = {'State/Province':'State', 'Country/Region':'Region'})
#old->new
sales.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Region', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [19]:
# Create another column : stateGroup1 by first character of the  state
def state_group(state):
    first = state[0].upper()
    if 'A' <= first <= 'G':
        return 'A-G'
    elif 'I' <= first <= 'M':
        return 'I-M'
    elif 'N' <= first <= 'Z':
        return 'N-Z'
    return 'Other'

In [20]:
sales['State_Group1'] = sales['State'].apply(state_group)
sales[['State','State_Group1']]

                      State State_Group1
0                     Texas          N-Z
1                  Illinois          I-M
2                  Illinois          I-M
3                  Illinois          I-M
4              Pennsylvania          N-Z
...                     ...          ...
10189              New York          N-Z
10190            California          A-G
10191              Colorado          A-G
10192              New York          N-Z
10193  Prince Edward Island          N-Z

[10194 rows x 2 columns]

In [21]:
sales[['State','State_Group1']].groupby('State_Group1').agg('count')

              State
State_Group1
A-G            3331
I-M            1635
N-Z            5228

###  Sets

In [24]:
sales['Profit'].dtypes

dtype('float64')

In [26]:
#### M1
sales['Profit_Category1'] = np.select(  [  
    sales['Profit'] < 0, sales['Profit'].between(0, 100),
    sales['Profit'].between(100, 500), sales['Profit'] > 500 ], 
    ['Loss','Low Profit','Medium Profit','High Profit' ], default='Unknown')
sales[['Profit', 'Profit_Category1']].head()

    Profit Profit_Category1
0   5.5512       Low Profit
1  -5.4870             Loss
2   4.2717       Low Profit
3 -64.7748             Loss
4   4.8840       Low Profit

In [27]:
### M2
sales['Profit_Category2'] = pd.qcut( sales['Profit'],  q=4, \
  labels=['Loss/Very Low', 'Low Profit', 'Medium Profit', 'High Profit'])
sales[['Profit', 'Profit_Category1', 'Profit_Category2']].head()

    Profit Profit_Category1 Profit_Category2
0   5.5512       Low Profit       Low Profit
1  -5.4870             Loss    Loss/Very Low
2   4.2717       Low Profit       Low Profit
3 -64.7748             Loss    Loss/Very Low
4   4.8840       Low Profit       Low Profit

### Sets - Top 3 States 
- Tableau
- 1. Right-click State → Create → Set
- 2. Top tab
- 3. Select Top 5 by Sum(Sales)
- 4. Use the set field in the view (IN = True, OUT = False).

In [29]:
# Get top 5 states by total sales
top_5_states = (sales.groupby('State')['Sales'].sum()
    .nlargest(5).index)
top_5_states

Index(['California', 'New York', 'Texas', 'Washington', 'Pennsylvania'], dtype='object', name='State')

In [30]:
sales['Top_5_State'] = sales['State'].isin(top_5_states)

In [31]:
sales[['State', 'Sales', 'Top_5_State']].head()

          State    Sales  Top_5_State
0         Texas   16.448         True
1      Illinois    3.540        False
2      Illinois   11.784        False
3      Illinois  272.736        False
4  Pennsylvania   19.536         True

In [32]:
list(top_5_states)

['California', 'New York', 'Texas', 'Washington', 'Pennsylvania']

In [40]:
sales[['State', 'Sales', 'Top_5_State']].groupby(['Top_5_State','State'])['Sales']. \
    sum().sort_index(ascending=False)

Top_5_State  State
True         Washington                   138641.2700
             Texas                        170188.0458
             Pennsylvania                 116511.9140
             New York                     310876.2710
             California                   457687.6315
False        Wyoming                        1603.1360
             Wisconsin                     32114.6100
             West Virginia                  1209.8240
             Virginia                      70636.7200
             Vermont                        8929.3700
             Utah                          11220.0560
             Tennessee                     30661.8730
             South Dakota                   1315.5600
             South Carolina                 8481.7100
             Saskatchewan                    132.3980
             Rhode Island                  22627.9560
             Quebec                         3826.9600
             Prince Edward Island           1087.9160
             Oregon                        17431.1500
             Ontario                        7009.0120
             Oklahoma                      19683.3900
             Ohio                          78258.1360
             Nova Scotia                     382.1440
             North Dakota                    919.9100
             North Carolina                55603.1640
             Newfoundland and Labrador       515.2000
             New Mexico                     4783.5220
             New Jersey                    35764.3120
             New Hampshire                  7292.5240
             New Brunswick                   225.6960
             Nevada                        16729.1020
             Nebraska                       7464.9300
             Montana                        5589.3520
             Missouri                      22205.1500
             Mississippi                   10771.3400
             Minnesota                     29863.1500
             Michigan                      76269.6140
             Massachusetts                 28634.4340
             Maryland                      23705.5230
             Manitoba                       1930.7820
             Maine                          1270.5300
             Louisiana                      9217.0300
             Kentucky                      36591.7500
             Kansas                         2914.3100
             Iowa                           4579.7600
             Indiana                       53555.3600
             Illinois                      80166.1010
             Idaho                          4382.4860
             Georgia                       49095.8400
             Florida                       89473.7080
             District of Columbia           2865.0200
             Delaware                      27451.0690
             Connecticut                   13384.3570
             Colorado                      32108.1180
             British Columbia               2763.2000
             Arkansas                      11678.1300
             Arizona                       35282.0010
             Alberta                       11460.1860
             Alabama                       19510.6400
Name: Sales, dtype: float64

In [41]:
sales[['State', 'Sales', 'Top_5_State']].groupby(['Top_5_State','State'])['Sales']. \
    sum().sort_values(ascending=False)

Top_5_State  State
True         California                   457687.6315
             New York                     310876.2710
             Texas                        170188.0458
             Washington                   138641.2700
             Pennsylvania                 116511.9140
False        Florida                       89473.7080
             Illinois                      80166.1010
             Ohio                          78258.1360
             Michigan                      76269.6140
             Virginia                      70636.7200
             North Carolina                55603.1640
             Indiana                       53555.3600
             Georgia                       49095.8400
             Kentucky                      36591.7500
             New Jersey                    35764.3120
             Arizona                       35282.0010
             Wisconsin                     32114.6100
             Colorado                      32108.1180
             Tennessee                     30661.8730
             Minnesota                     29863.1500
             Massachusetts                 28634.4340
             Delaware                      27451.0690
             Maryland                      23705.5230
             Rhode Island                  22627.9560
             Missouri                      22205.1500
             Oklahoma                      19683.3900
             Alabama                       19510.6400
             Oregon                        17431.1500
             Nevada                        16729.1020
             Connecticut                   13384.3570
             Arkansas                      11678.1300
             Alberta                       11460.1860
             Utah                          11220.0560
             Mississippi                   10771.3400
             Louisiana                      9217.0300
             Vermont                        8929.3700
             South Carolina                 8481.7100
             Nebraska                       7464.9300
             New Hampshire                  7292.5240
             Ontario                        7009.0120
             Montana                        5589.3520
             New Mexico                     4783.5220
             Iowa                           4579.7600
             Idaho                          4382.4860
             Quebec                         3826.9600
             Kansas                         2914.3100
             District of Columbia           2865.0200
             British Columbia               2763.2000
             Manitoba                       1930.7820
             Wyoming                        1603.1360
             South Dakota                   1315.5600
             Maine                          1270.5300
             West Virginia                  1209.8240
             Prince Edward Island           1087.9160
             North Dakota                    919.9100
             Newfoundland and Labrador       515.2000
             Nova Scotia                     382.1440
             New Brunswick                   225.6960
             Saskatchewan                    132.3980
Name: Sales, dtype: float64