# Tableau - Joins
- https://help.tableau.com/current/pro/desktop/en-us/joining_tables.htm

## Python - Join
#conn = create_engine("mysql+pymysql://root:xxx@localhost:3306/piit")

In [7]:
import pandas as pd
#import mysql.connector
from sqlalchemy import create_engine
#conn = mysql.connector.connect( host='localhost', user='root', password='Mysql@123', database='dup')
conn = create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/dup")
conn

Engine(mysql+pymysql://piuser:***@localhost:3306/dup)

In [13]:
empQ = "SELECT * FROM emp"
empdf = pd.read_sql(empQ, conn)
empdf.head()

    empno   ename       job     mgr    hiredate     sal    comm  deptno
0  7369.0   SMITH     CLERK  7902.0  1980-12-17   800.0     NaN    20.0
1  7499.0   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2  7521.0    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
3  7566.0   JONES   MANAGER  7839.0  1981-04-02  2975.0     NaN    20.0
4  7654.0  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0

In [14]:
deptQ = "SELECT * FROM dept"
deptdf = pd.read_sql(deptQ, conn)
deptdf.head()

   deptno       dname       loc
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON

In [16]:
#empDept = pd.merge(empdf, deptdf, on='deptno')
#empDept

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7369.0,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20.0,RESEARCH,DALLAS
1,7499.0,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30.0,SALES,CHICAGO
2,7521.0,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30.0,SALES,CHICAGO
3,7566.0,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20.0,RESEARCH,DALLAS
4,7654.0,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30.0,SALES,CHICAGO
5,7698.0,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,NaN,30.0,SALES,CHICAGO
6,7782.0,CLARK,MANAGER,7839.0,1981-06-09,2450.0,NaN,10.0,ACCOUNTING,NEW YORK
7,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS
8,7839.0,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10.0,ACCOUNTING,NEW YORK
9,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,SALES,CHICAGO
10,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS
11,7900.0,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30.0,SALES,CHICAGO
12,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,RESEARCH,DALLAS
13,7934.0,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10.0,ACCOUNTING,NEW YORK

In [17]:
empdf['deptno'] = empdf['deptno'].astype(int).astype(str)
deptdf['deptno'] = deptdf['deptno'].astype(int).astype(str)

In [18]:
empDeptDF = pd.merge(empdf, deptdf, on='deptno')

In [19]:
empDeptDF

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7369.0,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
1,7499.0,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
2,7521.0,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO
3,7566.0,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS
4,7654.0,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO
5,7698.0,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,NaN,30,SALES,CHICAGO
6,7782.0,CLARK,MANAGER,7839.0,1981-06-09,2450.0,NaN,10,ACCOUNTING,NEW YORK
7,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS
8,7839.0,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,ACCOUNTING,NEW YORK
9,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO
10,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS
11,7900.0,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30,SALES,CHICAGO
12,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20,RESEARCH,DALLAS
13,7934.0,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,ACCOUNTING,NEW YORK