# Tableau - LOD
- https://help.tableau.com/current/pro/desktop/en-us/calculations_calculatedfields_lod.htm

## LODs in Tableau

### LOD - FIXED
    - create as calculated field
    - Create Calculate field by name of
    - LOD Customer Sales and put this notation in text box {FIXED [Customer Name] : SUM([Sales])}

### LOD Region Sales
    - {FIXED [Region] : SUM([Sales]) }

### LOD Customer Sales
- {FIXED [Customer Name] : SUM([Sales])}

### LOD Customer First Order
- { FIXED [Customer Name] : MIN([Order Date]) }

### How to use in Sheets
- Case-1
    - Part - 1
        - Rows - Customer Name
        - Columns - Sales : Sum(Sales)
    - Part -2
        - Add Region to Rows, next to customer name
        - This will show Region wise sales of each customer
        - Add LOD Customer Sales to Columns
        - This will add another dimension to the sheet showing total sales by customer
        - Compare Region Sales of each customer with its total Sales in all regions

In [ ]:
## Python - LOD

In [ ]:
# Data
import numpy as np
import pandas as pd
import datetime as dt

In [ ]:
url1 = 'https://raw.githubusercontent.com/dupadhyaya/piit/refs/heads/main/data/superstore_orders.csv'
print(url1)

In [ ]:
sales = pd.read_csv(url1)
sales.shape

In [ ]:
sales.head()

In [ ]:
sales.columns

In [ ]:
sales.info()

In [185]:
# sales by each customer
custTotal = sales[['Customer Name','Sales']].groupby('Customer Name')['Sales']\
    .agg('sum').round(0).reset_index().rename(columns= {'Sales':'Total'})
custTotal.head()

     Customer Name    Total
0    Aaron Bergman   886.00
1    Aaron Hawkins 1,745.00
2   Aaron Smayling 3,051.00
3  Adam Bellavance 7,756.00
4        Adam Hart 3,250.00

In [186]:
# Sort sales in decreasing order
custTotal.sort_values(by='Total', ascending=False).head(10)

          Customer Name     Total
693         Sean Miller 25,043.00
737        Tamara Chand 19,052.00
629        Raymond Buch 15,117.00
764        Tom Ashbrook 14,596.00
6         Adrian Barton 14,474.00
446        Ken Lonsdale 14,175.00
678        Sanjit Chand 14,142.00
336        Hunter Lopez 12,873.00
679        Sanjit Engle 12,209.00
157  Christopher Conant 12,129.00

In [187]:
#group Customer Sales by Region
custRegion = sales[['Customer Name','Region','Sales']].groupby(['Customer Name','Region'])['Sales'] \
    .agg('sum').round(0).reset_index()
custRegion.head()

   Customer Name   Region    Sales
0  Aaron Bergman  Central   577.00
1  Aaron Bergman     West   310.00
2  Aaron Hawkins     East   330.00
3  Aaron Hawkins    South    86.00
4  Aaron Hawkins     West 1,328.00

In [188]:
# join total Sales and region wise sales like LOD
custTotalRegion = pd.merge(custTotal, custRegion, on='Customer Name', how='inner')
custTotalRegion.shape

(2508, 4)

In [189]:
custTotalRegion.head()

   Customer Name    Total   Region    Sales
0  Aaron Bergman   886.00  Central   577.00
1  Aaron Bergman   886.00     West   310.00
2  Aaron Hawkins 1,745.00     East   330.00
3  Aaron Hawkins 1,745.00    South    86.00
4  Aaron Hawkins 1,745.00     West 1,328.00

In [190]:
custTotalRegion.groupby('Customer Name').head()

           Customer Name    Total   Region    Sales
0          Aaron Bergman   886.00  Central   577.00
1          Aaron Bergman   886.00     West   310.00
2          Aaron Hawkins 1,745.00     East   330.00
3          Aaron Hawkins 1,745.00    South    86.00
4          Aaron Hawkins 1,745.00     West 1,328.00
...                  ...      ...      ...      ...
2503    Zuschuss Carroll 8,026.00    South 1,471.00
2504    Zuschuss Carroll 8,026.00     West 2,641.00
2505  Zuschuss Donatelli 1,494.00  Central   331.00
2506  Zuschuss Donatelli 1,494.00    South   857.00
2507  Zuschuss Donatelli 1,494.00     West   306.00

[2508 rows x 4 columns]

In [191]:
## Index method
custTotal_idx = custTotal.set_index('Customer Name')
custRegion_idx = custRegion.set_index('Customer Name')
custRegion_idx.head()

                Region    Sales
Customer Name
Aaron Bergman  Central   577.00
Aaron Bergman     West   310.00
Aaron Hawkins     East   330.00
Aaron Hawkins    South    86.00
Aaron Hawkins     West 1,328.00

In [192]:
custTotalRegion = custTotal_idx.join( custRegion_idx, how='inner')
custTotalRegion.head()

                 Total   Region    Sales
Customer Name
Aaron Bergman   886.00  Central   577.00
Aaron Bergman   886.00     West   310.00
Aaron Hawkins 1,745.00     East   330.00
Aaron Hawkins 1,745.00    South    86.00
Aaron Hawkins 1,745.00     West 1,328.00

- For pandas:
    * merge() → SQL-style joins on columns.
    * join() → Faster and cleaner when joining on indexes.
    * map() → Best when bringing a single aggregated value (like your customer total) into another DataFrame.

In [193]:
custRegion['Total'] = custRegion['Customer Name']\
    .map(custTotal.set_index('Customer Name')['Total'])
custRegion.sort_values(by='Total', ascending=False).head()

     Customer Name   Region     Sales     Total
2174   Sean Miller     West     10.00 25,043.00
2171   Sean Miller  Central    526.00 25,043.00
2172   Sean Miller     East    837.00 25,043.00
2173   Sean Miller    South 23,669.00 25,043.00
2315  Tamara Chand     West      7.00 19,052.00

In [194]:
#!pip install ipydatagrid
#from ipydatagrid import DataGrid
#DataGrid(custRegion)

In [195]:
#!pip install itables
from itables import show

In [196]:
show(custRegion)

In [197]:
GT(custRegion.head())

GT(_tbl_data=   Customer Name   Region    Sales    Total
0  Aaron Bergman  Central   577.00   886.00
1  Aaron Bergman     West   310.00   886.00
2  Aaron Hawkins     East   330.00 1,745.00
3  Aaron Hawkins    South    86.00 1,745.00
4  Aaron Hawkins     West 1,328.00 1,745.00, _body=<great_tables._gt_data.Body object at 0x15133a930>, _boxhead=Boxhead([ColInfo(var='Customer Name', type=<ColInfoTypeEnum.default: 1>, column_label='Customer Name', column_align='left', column_width=None), ColInfo(var='Region', type=<ColInfoTypeEnum.default: 1>, column_label='Region', column_align='left', column_width=None), ColInfo(var='Sales', type=<ColInfoTypeEnum.default: 1>, column_label='Sales', column_align='right', column_width=None), ColInfo(var='Total', type=<ColInfoTypeEnum.default: 1>, column_label='Total', column_align='right', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x15133a2d0>, _spanners=Spanners([]), _heading=Heading(title=None, subtitle=None, preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x15133b290>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x15133b860>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x15133ad80>, _formats=[], _substitutions=[], _col_merge=[], _transforms=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), summary_row_padding=OptionsInfo(scss=True, category='summary_row', type='px', value='8px'), summary_row_padding_horizontal=OptionsInfo(scss=True, category='summary_row', type='px', value='5px'), summary_row_background_color=OptionsInfo(scss=True, category='summary_row', type='value', value=None), summary_row_text_transform=OptionsInfo(scss=True, category='summary_row', type='value', value='inherit'), summary_row_border_style=OptionsInfo(scss=True, category='summary_row', type='value', value='solid'), summary_row_border_width=OptionsInfo(scss=True, category='summary_row', type='px', value='2px'), summary_row_border_color=OptionsInfo(scss=True, category='summary_row', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), footnotes_marks=OptionsInfo(scss=False, category='footnotes', type='values', value='numbers'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)

In [198]:
## LOD - Minimum Order date
sales[['Customer Name', 'Order Date', 'Sales']].head(10)

   Customer Name Order Date    Sales
0  Darren Powers   03/01/23    16.45
1  Phillina Ober   04/01/23     3.54
2  Phillina Ober   04/01/23    11.78
3  Phillina Ober   04/01/23   272.74
4     Mick Brown   05/01/23    19.54
5  Maria Etezadi   06/01/23 2,573.82
6  Maria Etezadi   06/01/23     5.48
7  Jack O'Briant   06/01/23    12.78
8  Maria Etezadi   06/01/23   609.98
9  Maria Etezadi   06/01/23    31.12

In [199]:
sales['Order Date']

0        03/01/23
1        04/01/23
2        04/01/23
3        04/01/23
4        05/01/23
           ...
10189    30/12/26
10190    30/12/26
10191    30/12/26
10192    30/12/26
10193    30/12/26
Name: Order Date, Length: 10194, dtype: object

In [200]:
pd.to_datetime(sales['Order Date'],format='%d/%m/%y', dayfirst=True)

0       2023-01-03
1       2023-01-04
2       2023-01-04
3       2023-01-04
4       2023-01-05
           ...
10189   2026-12-30
10190   2026-12-30
10191   2026-12-30
10192   2026-12-30
10193   2026-12-30
Name: Order Date, Length: 10194, dtype: datetime64[ns]

In [201]:
pd.to_datetime(sales['Order Date'],format='%d/%m/%y', dayfirst=True) #.dt.date

0       2023-01-03
1       2023-01-04
2       2023-01-04
3       2023-01-04
4       2023-01-05
           ...
10189   2026-12-30
10190   2026-12-30
10191   2026-12-30
10192   2026-12-30
10193   2026-12-30
Name: Order Date, Length: 10194, dtype: datetime64[ns]

In [202]:
sales['Order Date'] = pd.to_datetime(sales['Order Date'],format='%d/%m/%y', \
                                     dayfirst=True).dt.normalize()
sales['Ship Date'] = pd.to_datetime(sales['Ship Date'],format='%d/%m/%y', \
                                     dayfirst=True).dt.normalize()
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(14)
memory usage: 1.6+ MB

## Range of Date and numeric values to check version of data

In [203]:
pd.set_option('display.float_format', '{:,.2f}'.format)

In [204]:
# Numeric columns
num_range = sales.select_dtypes(include='number').agg(['min', 'max','sum']).T
# Date columns
date_range = sales.select_dtypes(include='datetime').agg(['min', 'max','count']).T
print("Numeric Columns")
display(num_range)
print("Date Columns")
display(date_range)

Numeric Columns

               min       max           sum
Row ID        1.00 10,194.00 51,963,915.00
Sales         0.44 22,638.48  2,326,534.35
Quantity      1.00     14.00     38,654.00
Discount      0.00      0.80      1,583.99
Profit   -6,599.98  8,399.98    292,296.81

Date Columns

                            min                  max  count
Order Date  2023-01-03 00:00:00  2026-12-30 00:00:00  10194
Ship Date   2023-01-07 00:00:00  2027-01-05 00:00:00  10194

In [ ]:
sales.describe()

In [ ]:
custFirstOrder = (sales.groupby('Customer Name', as_index=False)['Order Date'].min()\
    .rename(columns={'Order Date': 'First Order Date'}))
custFirstOrder[['Customer Name', 'First Order Date']].sort_values(by='First Order Date')

In [ ]:
custSummary = (sales.groupby('Customer Name', as_index=False).\
    agg(First_Order_Date =('Order Date','min'), Total_Sales = ('Sales','sum')))
custSummary.head()

In [ ]:
custSummary[['Customer Name', 'Total_Sales', 'First_Order_Date']].\
    sort_values(by=['Total_Sales', 'First_Order_Date'], ascending=[False,True])

## EndHere